### ISSUE TITLE
Открепленная подпись

### ISSUE THREAD

**Issue by neuspeed** [Infotecs/CSharpViPNetCSP#2]
Приветствую. Подскажите, пожалуйста, как взаимодействовать с помощью вашего API с открепленной подписью в формате .sig. Необходимо проверять архив .zip и его подпись .zip.sig. Из примеров не очень понятно, так как там подпись создается в процессе обработки данных.

**Comment by jia3ep** [comment]
Здравствуйте. Если вам нужна поддержка по продуктам компании, то вы можете задать вопросы в профильном форуме https://infotecs.ru/forum/
